---
title: "Linear Combination Normal Distribution"
author: "Anthony Morciglio"
date: "10/21/2025"
output: html_document
---

## Linear Combination of Independent Normal Random Variables

In this R Markdown section, we demonstrate that a linear combination of independent Normal random variables is itself Normally distributed.  

The procedure is as follows:

1. **Randomly generate parameters**: 
   - Each of the three independent Normal random variables \(X_1, X_2, X_3\) is assigned a random mean (\(\mu_i\)) and variance (\(\sigma_i^2\)).  
   - These parameters are generated uniformly within reasonable ranges to ensure variability between the distributions.

2. **Simulate random draws**:  
   - For each variable, generate a large sample (e.g., 10,000 points) from its corresponding Normal distribution using `rnorm()`.

3. **Define a linear combination**:  
   - Arbitrary constants \(a_1, a_2, a_3\) are chosen to form a linear combination
     \[
     Z = a_1 X_1 + a_2 X_2 + a_3 X_3.
     \]  

4. **Compute and visualize**:  
   - Compute the sample mean and variance of the resulting linear combination.  
   - Plot a histogram of \(Z\) overlaid with the theoretical Normal density function using the computed mean and variance.  

The goal is to empirically illustrate that the resulting linear combination is approximately Normally distributed, as predicted by theory.


```{r, echo=TRUE, message=FALSE, warning=FALSE}
# Set seed
set.seed(456)

# Number of samples
n <- 10000

# Reduced variability for means and standard deviations
mu <- runif(3, -1, 1)
sigma <- runif(3, 0.8, 1.2)

# Simulate independent normal variables
X1 <- rnorm(n, mean=mu[1], sd=sigma[1])
X2 <- rnorm(n, mean=mu[2], sd=sigma[2])
X3 <- rnorm(n, mean=mu[3], sd=sigma[3])

# Linear combination coefficients
a <- c(1.5, -1, 0.5)

# Linear combination
Z <- a[1]*X1 + a[2]*X2 + a[3]*X3

# Compute statistics for linear combination
mean_Z <- mean(Z)
var_Z <- var(Z)

# Plot individual distributions with limited transparency
hist(X1, breaks=40, probability=TRUE, col=rgb(1,0,0,0.4), border="white",
     xlim=range(c(X1,X2,X3,Z)), ylim=c(0,0.5),
     main="Individual Normals and Linear Combination", xlab="Value")
hist(X2, breaks=40, probability=TRUE, col=rgb(0,1,0,0.4), border="white", add=TRUE)
hist(X3, breaks=40, probability=TRUE, col=rgb(0,0,1,0.4), border="white", add=TRUE)

# Overlay linear combination histogram
hist(Z, breaks=50, probability=TRUE, col=rgb(0.8,0.8,0.8,0.5), border="white", add=TRUE)

# Overlay theoretical density of linear combination
curve(dnorm(x, mean=mean_Z, sd=sqrt(var_Z)), col="black", lwd=2, add=TRUE)

# Add legend
legend("topright",
       legend=c("X1","X2","X3","Linear Combination","Theoretical Density"),
       fill=c(rgb(1,0,0,0.4), rgb(0,1,0,0.4), rgb(0,0,1,0.4), rgb(0.8,0.8,0.8,0.5), NA),
       border=NA, lty=c(NA,NA,NA,NA,1), col=c(NA,NA,NA,NA,"black"), lwd=c(NA,NA,NA,NA,2))

```

